#* ###########################
#* #### Stage 1: Builder #####
#* ###########################
FROM node:14.20.1-alpine3.16 AS builder
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --pure-lockfile

COPY . ./
RUN npm run build

#* ###########################
#* ##### Stage 2: Nginx ######
#* ###########################
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]
