POST {{root}}/proposals
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..gn49yTE5_ciFhp1L.yldL_wykp-LbaRtdV_h427DkbhtNKC6rQ5ck3WHj8ofDvs21vqJsRUcRiaNZjhhyF3XjBkX6WhelqEF7YKHy3KRguL6d8OilzeJsuQ0BP78ZoZz-yAZpsdTeFPV2cF_9O1_UiklzTfLcm3ranHO7oSfiVLcvUlNhMpT0SDBDqMh5MypdiPiAew0j71YJRKEO35I1EwV5vRsHB-QpYPVbTfJF3gQAjdQroFjjfb6znTsuBACws-G37f4kglvB6np-jA4WjQhSiL_bjL2Q7PZ9SSVtRKfbC9yoBWBMB-Ac6Qu3l6HFpYkEe_Q6wtMw_uzg1tr6sSRbB_tl9wK20yn_SZPLRTxAw0h3-4nG.2cR0xQ8RG9rCVNvUYWu13g
X-XSRF-TOKEN: f64c8fa0-158b-4b59-989b-cc464362daa7

--boundary
Content-Disposition: form-data; name="dto"; filename="dto.json"

< proposal_example_files/dto.json
--boundary
Content-Disposition: form-data; name="file"; filename="proposal_example_files/image_proposal.png"

< proposal_example_files/image_proposal.png
--boundary
Content-Disposition: form-data; name="contactPerson"
Content-Type: text/plain
{{contact_person_mail}}