POST {{root}}/contactperson
Content-Type: application/json

{
  "name": "Pruebacp",
  "surname": "contactpersonPruebaEsal",
  "phoneNumber": "+850 3423423423",
  "email": "{{contact_person_mail}}",
  "password": "{{general_password}}"
}