export enum Role {
  VOLUNTEER = 'VOLUNTEER',
  VOLUNTEER_NOT_CONFIRMED = 'VOLUNTEER_NOT_CONFIRMED',
  CONTACT_PERSON = 'CONTACT_PERSON',
  CONTACT_PERSON_NOT_CONFIRMED = 'CONTACT_PERSON_NOT_CONFIRMED',
  REVISER = 'REVISER',
  NONE = 'NONE',
}
