export const LIST_MUNICIPALITY = [
  'Santa Cruz de Tenerife',
  'San Cristobal de La Laguna',
  'Arona',
  'Adeje',
  'Granadilla de Abona',
  'La Orotava',
  'Los Realejos',
  'Puerto de La Cruz',
  'Candelaria',
  'Tacoronte',
  'Icod de Los Vinos',
  'Guía de Isora',
  'Güímar',
  'San Miguel de Abona',
  'El Rosario',
  'Santa Úrsula',
  'Tegueste',
  'Santiago del Teide',
  'El sauzal',
  'La Victoria de Acentejo',
  'La Matanza de Acentejo',
  'Arico',
  'La Guancha',
  'Arafo',
  'San Juan de La Rambla',
  'Garachico',
  'Los Silos',
  'Buenavista del Norte',
  'Fasnia',
  'El Tanque',
  'Vilaflor de Chasna',
];
